; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:adafruit_feather_esp32s3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = adafruit_feather_esp32s3
framework = arduino
monitor_speed = 115200
build_type = release
build_flags =
	-I$PROJECT_PACKAGES_DIR/framework-arduinoespressif32-libs/esp32s3/include/esp_eth/include
	-DCORE_DEBUG_LEVEL=0
	-DDEBUG_AUDIO=0
	-Wl,--gc-sections
lib_ignore = 
	WiFiNINA_-_Adafruit_Fork
	WiFi101
	DHT sensor library
	Adafruit Unified Sensor
	Adafruit BME280 Library
	Adafruit Si7021 Library
	Adafruit SGP30 Sensor
	Adafruit LIS3DH
	Adafruit VEML6070 Library
	Ethernet
	ESP32Servo
	WiFiManager
	ArduinoJson
	Adafruit NeoPixel
lib_deps = 
	adafruit/Adafruit IO Arduino @ ^4.3.4
	fastled/FastLED@^3.10.3
	sensirion/Sensirion Core@^0.7.3
