/*
 * THIS FILE IS AUTOMATICALLY GENERATED
 *
 * Generator:     sensirion-driver-generator 1.1.2
 * Product:       sen66
 * Model-Version: 1.6.0
 */
/*
 * Copyright (c) 2025, Sensirion AG
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * * Neither the name of Sensirion AG nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
#include <Arduino.h>
#include <SensirionI2cSen66.h>
#include <Wire.h>
#include "config.h"
#include "AdafruitIO_WiFi.h"

// macro definitions
// make sure that we use the proper definition of NO_ERROR
#ifdef NO_ERROR
#undef NO_ERROR
#endif
#define NO_ERROR 0

// Publish interval in milliseconds for round-robin
#define PUBLISH_INTERVAL_MS 2000

SensirionI2cSen66 sensor;

static char errorMessage[64];
static int16_t error;

// Adafruit IO connection
AdafruitIO_WiFi io(IO_USERNAME, IO_KEY, WIFI_SSID, WIFI_PASS);

// Adafruit IO feeds (under "envirocube" group)
AdafruitIO_Feed *pm1Feed = io.feed("envirocube.pm1");
AdafruitIO_Feed *pm25Feed = io.feed("envirocube.pm2-5");
AdafruitIO_Feed *tempFeed = io.feed("envirocube.temperature");
AdafruitIO_Feed *humidFeed = io.feed("envirocube.humidity");
AdafruitIO_Feed *co2Feed = io.feed("envirocube.co2");

unsigned long lastPublishTime = 0;

bool isValidPm(float val) { return val > 0.0f && val < 1000.0f; }
bool isValidHumidity(float val) { return val > 0.0f && val < 100.0f; }
bool isValidTemperature(float val) { return val > -40.0f && val < 70.0f; }
bool isValidVoc(float val) { return val >= 0.0f; }
bool isValidNox(float val) { return val >= 0.0f; }
bool isValidCo2(uint16_t val) { return val > 0 && val < 40000; }

int currSensor = 0;

void setup() {

    Serial.begin(115200);
    while (!Serial) {
        delay(100);
    }
    Wire.begin();
    sensor.begin(Wire, SEN66_I2C_ADDR_6B);

    error = sensor.deviceReset();
    if (error != NO_ERROR) {
        Serial.print("Error trying to execute deviceReset(): ");
        errorToString(error, errorMessage, sizeof errorMessage);
        Serial.println(errorMessage);
        return;
    }
    delay(1200);
    int8_t serialNumber[32] = {0};
    error = sensor.getSerialNumber(serialNumber, 32);
    if (error != NO_ERROR) {
        Serial.print("Error trying to execute getSerialNumber(): ");
        errorToString(error, errorMessage, sizeof errorMessage);
        Serial.println(errorMessage);
        return;
    }
    Serial.print("serialNumber: ");
    Serial.print((const char*)serialNumber);
    Serial.println();
    error = sensor.startContinuousMeasurement();
    if (error != NO_ERROR) {
        Serial.print("Error trying to execute startContinuousMeasurement(): ");
        errorToString(error, errorMessage, sizeof errorMessage);
        Serial.println(errorMessage);
        return;
    }

    Serial.print("Connecting to Adafruit IO");
    io.connect();
    while (io.status() < AIO_CONNECTED) {
        Serial.print(".");
        delay(500);
    }
    Serial.println();
    Serial.println(io.statusText());
}

void loop() {
    io.run();

    float massConcentrationPm1p0 = 0.0;
    float massConcentrationPm2p5 = 0.0;
    float massConcentrationPm4p0 = 0.0;
    float massConcentrationPm10p0 = 0.0;
    float humidity = 0.0;
    float temperature = 0.0;
    float vocIndex = 0.0;
    float noxIndex = 0.0;
    uint16_t co2 = 0;
    delay(1000);
    error = sensor.readMeasuredValues(
        massConcentrationPm1p0, massConcentrationPm2p5, massConcentrationPm4p0,
        massConcentrationPm10p0, humidity, temperature, vocIndex, noxIndex,
        co2);
    if (error != NO_ERROR) {
        Serial.print("Error trying to execute readMeasuredValues(): ");
        errorToString(error, errorMessage, sizeof errorMessage);
        Serial.println(errorMessage);
        return;
    }
    bool pm1Valid = isValidPm(massConcentrationPm1p0);
    bool pm25Valid = isValidPm(massConcentrationPm2p5);
    bool pm4Valid = isValidPm(massConcentrationPm4p0);
    bool pm10Valid = isValidPm(massConcentrationPm10p0);
    bool humidValid = isValidHumidity(humidity);
    bool tempValid = isValidTemperature(temperature);
    bool vocValid = isValidVoc(vocIndex);
    bool noxValid = isValidNox(noxIndex);
    bool co2Valid = isValidCo2(co2);

    Serial.println("--------------------------------");
    Serial.print(">massConcentrationPm1p0: ");
    Serial.println(pm1Valid ? String(massConcentrationPm1p0) : "INVALID");
    Serial.print(">massConcentrationPm2p5: ");
    Serial.println(pm25Valid ? String(massConcentrationPm2p5) : "INVALID");
    Serial.print(">massConcentrationPm4p0: ");
    Serial.println(pm4Valid ? String(massConcentrationPm4p0) : "INVALID");
    Serial.print(">massConcentrationPm10p0: ");
    Serial.println(pm10Valid ? String(massConcentrationPm10p0) : "INVALID");
    Serial.print(">humidity: ");
    Serial.println(humidValid ? String(humidity) : "INVALID");
    Serial.print(">temperature: ");
    Serial.println(tempValid ? String(temperature) : "INVALID");
    Serial.print(">vocIndex: ");
    Serial.println(vocValid ? String(vocIndex) : "INVALID");
    Serial.print(">noxIndex: ");
    Serial.println(noxValid ? String(noxIndex) : "INVALID");
    Serial.print(">co2: ");
    Serial.println(co2Valid ? String(co2) : "INVALID");

    // Publish in round-robin fashion to avoid free plan data limits
    if (millis() - lastPublishTime >= PUBLISH_INTERVAL_MS) {
        lastPublishTime = millis();
        Serial.println("Publishing to Adafruit IO...");
        if (pm1Valid && currSensor == 0) pm1Feed->save(massConcentrationPm1p0);
        if (pm25Valid && currSensor == 1) pm25Feed->save(massConcentrationPm2p5);
        if (tempValid && currSensor == 2) tempFeed->save(temperature);
        if (humidValid && currSensor == 3) humidFeed->save(humidity);
        if (co2Valid && currSensor == 4) co2Feed->save(co2);
        currSensor = (currSensor + 1) % 5;
    }
}
